apiVersion: v1
kind: Secret
metadata:
  name: laravel-secret
type: Opaque
stringData:
  app_key: base64:2wC69cy6WO8aJEwZmI63aM+H25ETlXOa2VVuDBxf75A=
  db_database: argocd
  db_username: root
  db_password:
